# ============== Stage 1 ================
FROM node:22.14.0-alpine As development

RUN npm install -g pnpm

WORKDIR /usr/src/app

COPY package.json ./
COPY pnpm-lock.yaml ./
COPY tsconfig.json tsconfig.json
COPY nest-cli.json nest-cli.json

COPY apps/store apps/store
COPY libs libs

RUN pnpm install -r

RUN pnpm run build store
